name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ghcr.io/logsem/clutch/docker-x86-64
      max-parallel: 4
      # don't cancel all in-progress jobs if one matrix job fails:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'rocq-verusbelt.opam'
          custom_image: ${{ matrix.image }}
          install: |
            startGroup "Pin VerusBelt-specific dependencies"
              apt-get install rsync -y
              opam pin add -n -y -k path $PACKAGE $WORKDIR
              opam reinstall --forget-pending --yes
              opam install --confirm-level=unsafe-yes -j 2 $PACKAGE \
                --deps-only --ignore-constraints-on=rocq-stdpp
            endGroup
          script: |
            startGroup Build
              make -j2
            endGroup
          uninstall: |
            make clean

